name: deploy web

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: yarn --frozen-lockfile
      - run: yarn build
      - uses: actions/upload-artifact@v3
        with:
          name: my_site
          path: dist
      - uses: actions/upload-pages-artifact@v1
        with:
          path: dist
          
  deploy:
    needs: build
    runs-on: ubuntu-latest 
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/deploy-pages@v1
        id: deployment
